# Generated by Django 2.2.10 on 2021-02-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel',
            field=models.ImageField(blank=True, null=True, upload_to='carousel-img'),
        ),
    ]
