# Generated by Django 2.2.10 on 2021-02-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210215_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_promotion',
            name='card_img',
            field=models.ImageField(blank=True, null=True, upload_to='card-img'),
        ),
    ]
